// src/app/(pages)/seller/_data/sellersData.js

export const sellersData = [
  {
    id: 1,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: true,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
  {
    id: 2,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: false,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
  {
    id: 3,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: false,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
  {
    id: 4,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: false,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
  {
    id: 5,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: false,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
  {
    id: 6,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: false,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
  {
    id: 7,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: false,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
  {
    id: 8,
    name: "NovaStore",
    slug: "nova-store",
    avatar: "/seller_avater.jpg",
    cover: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=80",
    isVerified: true,
    isFeatured: false,
    sales: "2.4K+ Sales",
    productsCount: "126 Products",
    rating: 4.5,
    reviewsCount: "350+ Reviews",
    platforms: [
      { name: "Facebook", icon: "/logo_image/facebook.png" },
      { name: "Figma", icon: "/logo_image/figma.png" },
      { name: "Apple", icon: "/logo_image/apple.png" },
    ],
    extraPlatformsCount: "120+",
  },
];
